# Generated by Django 5.1.6 on 2025-03-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='channel_avatars'),
        ),
    ]
