# Generated by Django 5.1.6 on 2025-05-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='channel_avatar',
        ),
        migrations.AddField(
            model_name='channel',
            name='avatar_s3_bucket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='avatar_s3_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
