# Generated by Django 5.1.6 on 2025-05-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_remove_channel_channel_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='avatar_s3_bucket',
        ),
    ]
