# Generated by Django 5.1.6 on 2025-07-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_remove_channel_avatar_s3_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='country',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
