# Generated by Django 5.1.6 on 2025-09-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_alter_channel_country_alter_channel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(max_length=40, unique=True),
        ),
    ]
