# Generated by Django 5.1.6 on 2025-10-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_alter_channel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='avatar_s3_key',
            field=models.CharField(blank=True, help_text='Channel avatar S3 file key', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='country',
            field=models.CharField(blank=True, help_text='Country where the channel is located', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True, help_text='Channel description', null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(help_text='Channel name', max_length=100),
        ),
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(help_text='Channel slug', max_length=40, unique=True),
        ),
    ]
