services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    ports:
      - "80:80"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    command: certonly --standalone --email ${CERTBOT_EMAIL} -n --expand --agree-tos ${CERTBOT_DOMAINS}
