services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/test/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email ${CERTBOT_EMAIL} --test-cert --agree-tos -d ${CERTBOT_DOMAIN}