services:
  web:
    # container_name: yt-web-prod
    build:
      context: ..
      dockerfile: Dockerfile.prod
    image: yt-web-prod
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    volumes:
      - ../static:/app/static
    env_file:
      - ../.env
    deploy:
      replicas: 2
    command: "sh entrypoint.prod.sh"
    depends_on:
      #   celery:
      #  condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      pgbouncer:
        condition: service_started

  nginx:
    container_name: yt-nginx-prod
    image: nginx:latest
    entrypoint: ["sh", "/entrypoint.nginx.sh"]
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../${NGINX_CONFIG_NAME}:/etc/nginx/nginx.template.conf:ro
      - ../entrypoint.nginx.sh:/entrypoint.nginx.sh
      - ../static:/static:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    env_file:
      - ../.env
    depends_on:
      - web

  postgres:
    container_name: yt-postgres-prod
    image: postgres:17.2-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 30s
      retries: 5
    env_file:
      - ../.env

  pgbouncer:
    container_name: yt-pgbouncer-prod
    image: bitnami/pgbouncer:latest
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
      - POSTGRESQL_HOST=${POSTGRES_HOST}
      - POSTGRESQL_PORT=5432
      - PGBOUNCER_IGNORE_STARTUP_PARAMETERS=extra_float_digits
      - PGBOUNCER_DATABASE=${POSTGRES_DB}
      - PGBOUNCER_POOL_MODE=transaction
      - PGBOUNCER_MAX_CLIENT_CONN=100
      - PGBOUNCER_DEFAULT_POOL_SIZE=20
      - PGBOUNCER_RESERVE_POOL_SIZE=5
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    container_name: yt-redis-prod
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data/

  celery:
    # container_name: yt-celery-prod
    image: yt-web-prod
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    command: celery -A core.project.celery worker -l info -Q media-queue,email-queue
    env_file:
      - ../.env
    # deploy:
      # replicas: 2
      #healthcheck:
      #test: ["CMD", "celery", "-A", "core.project.celery", "status"]
      #interval: 30s
      #timeout: 10s
      #retries: 3
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  celery-beat:
    container_name: yt-celery-beat-prod
    image: yt-web-prod
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    command: sh -c "sleep 15 && celery -A core.project.celery beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    env_file:
      - ../.env
    depends_on:
      web:
        condition: service_started
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  flower:
    container_name: yt-flower-prod
    image: mher/flower:latest
    restart: unless-stopped
    command: celery --broker=redis://redis:${REDIS_PORT}/0 flower 
    volumes:
      - flower_data:/data
    env_file:
      - ../.env
    environment:
      - FLOWER_BASIC_AUTH=${FLOWER_USERNAME}:${FLOWER_PASSWORD}
      - FLOWER_PORT=5555
      - FLOWER_PERSISTENT=True
      - FLOWER_DB=/data/flower
    depends_on:
      redis:
        condition: service_healthy

volumes:
  postgres_data:
    name: yt_api_postgres_data
  redis_data:
    name: yt_api_redis_data
  flower_data:
    name: yt_api_flower_data
