services:
  web:
    # container_name: yt-web-prod
    build:
      context: ..
      dockerfile: Dockerfile.prod
    image: yt-web-prod
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    volumes:
      - ../static:/app/static
    env_file:
      - ../.env
        #deploy:
        #replicas: 2
    command: "sh entrypoint.prod.sh"
    depends_on:
      #   celery:
      #  condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      pgbouncer:
        condition: service_started

  nginx:
    container_name: yt-nginx-prod
    image: nginx:latest
    entrypoint: ["sh", "/entrypoint.nginx.sh"]
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../${NGINX_CONFIG_NAME}:/etc/nginx/nginx.template.conf:ro
      - ../entrypoint.nginx.sh:/entrypoint.nginx.sh
      - ../static:/static:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    env_file:
      - ../.env
    depends_on:
      - web

  postgres:
    container_name: yt-postgres-prod
    image: postgres:17.2-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 30s
      retries: 5
    env_file:
      - ../.env

  pgbouncer:
    container_name: yt-pgbouncer-prod
    restart: unless-stopped
    image: edoburu/pgbouncer:latest
    environment:
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=${POSTGRES_HOST}
      - DB_NAME=${POSTGRES_DB}
      - DB_PORT=5432
      - MAX_CLIENT_CONN=5000
      - DEFAULT_POOL_SIZE=90
      - RESERVE_POOL_SIZE=10
      - POOL_MODE=transaction
      - AUTH_TYPE=scram-sha-256
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    container_name: yt-redis-prod
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data/

  celery:
    # container_name: yt-celery-prod
    image: yt-web-prod
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    command: celery -A core.project.celery worker -l info -Q media-queue,email-queue
    env_file:
      - ../.env
        #deploy:
        #replicas: 2
      #healthcheck:
      #test: ["CMD", "celery", "-A", "core.project.celery", "status"]
      #interval: 30s
      #timeout: 10s
      #retries: 3
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  celery-beat:
    container_name: yt-celery-beat-prod
    image: yt-web-prod
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    command: sh -c "sleep 15 && celery -A core.project.celery beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    env_file:
      - ../.env
    depends_on:
      web:
        condition: service_started
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  celery-exporter:
    container_name: yt-celery-exporter-prod
    restart: unless-stopped
    image: danihodovic/celery-exporter:latest
    environment:
      - CE_BROKER_URL=redis://redis:${REDIS_PORT}/0

volumes:
  postgres_data:
    name: yt_api_postgres_data
  redis_data:
    name: yt_api_redis_data
  flower_data:
    name: yt_api_flower_data
