# Generated by Django 5.1.6 on 2025-10-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text="User's email address", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='otp_enabled',
            field=models.BooleanField(default=False, help_text='Controls whether email OTP verification is required for login'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(help_text="User's password", max_length=128),
        ),
    ]
