# Generated by Django 5.1.6 on 2025-10-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email_alter_customuser_otp_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(help_text='User password', max_length=128),
        ),
    ]
