services:
  web:
    container_name: yt-web
    build:
      context: .
    image: yt-web
    ports:
      - "${DJANGO_PORT}:8000"
    volumes:
      - ./core:/app/
    env_file:
      - .env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres
      - redis
  
  postgres:
    container_name: yt-postgres
    image: postgres:17.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env

  redis:
    container_name: yt-redis
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data/
  
  celery:
    container_name: yt-celery
    image: yt-web
    command: celery -A project worker -l info -Q media-queue,email-queue
    volumes:
      - ./core:/app/
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  celery-beat:
    container_name: yt-celery-beat
    image: yt-web
    command: celery -A project beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./core:/app/
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

volumes:
  postgres_data:
  redis_data: