# Generated by Django 5.1.6 on 2025-03-03 00:44

import django.db.models.deletion
from django.db import migrations, models

import core.apps.videos.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                (
                    'video_id',
                    models.CharField(
                        default=core.apps.videos.models.generate_video_link,
                        editable=False,
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('yt_link', models.CharField(blank=True, max_length=255)),
                (
                    'status',
                    models.CharField(
                        choices=[('PRIVATE', 'Private'), ('UNLISTED', 'Unlisted'), ('PUBLIC', 'Public')],
                        default='PUBLIC',
                        max_length=10,
                    ),
                ),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='channels.channel'
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='video_comments',
                        to='channels.channel',
                    ),
                ),
                (
                    'likes',
                    models.ManyToManyField(blank=True, related_name='liked_video_comments', to='channels.channel'),
                ),
                (
                    'video',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='videos.video'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='VideoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'channel',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='video_views',
                        to='channels.channel',
                    ),
                ),
                (
                    'video',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='views', to='videos.video'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='VideoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField()),
                (
                    'channel',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='liked_videos', to='channels.channel'
                    ),
                ),
                (
                    'video',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='videos.video'
                    ),
                ),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('channel', 'video'), name='unique_channel_video_like')],
            },
        ),
    ]
