# Generated by Django 5.1.6 on 2025-04-19 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_initial'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocomment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='videocomment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='videos.videocomment'),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='reply_level',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.CreateModel(
            name='VideoCommentLikeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_video_comments', to='channels.channel')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_items', to='videos.videocomment')),
            ],
        ),
        migrations.RemoveField(
            model_name='videocomment',
            name='likes',
        ),
        migrations.AddField(
            model_name='videocomment',
            name='likes',
            field=models.ManyToManyField(through='videos.VideoCommentLikeItem', to='channels.channel'),
        ),
    ]
