# Generated by Django 5.1.6 on 2025-03-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='upload_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('FINISHED', 'Finished')], default='PENDING'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
