# Generated by Django 5.1.6 on 2025-04-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_videocomment_updated_at_videocomment_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomment',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
