# Generated by Django 5.1.6 on 2025-04-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_videocomment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomment',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
