# Generated by Django 5.1.6 on 2025-03-18 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_channel_channel_avatar'),
        ('videos', '0003_video_upload_status_alter_video_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='channels.channel')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('channel', 'video'), name='unique_watch_history')],
            },
        ),
    ]
