# Generated by Django 5.1.6 on 2025-04-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_initial'),
        ('videos', '0004_alter_videocomment_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='videocommentlikeitem',
            constraint=models.UniqueConstraint(fields=('author', 'comment'), name='unique_comment_like'),
        ),
    ]
