# Generated by Django 5.1.6 on 2025-03-20 14:06

import django.db.models.deletion
from django.db import migrations, models

import core.apps.videos.models


class Migration(migrations.Migration):
    dependencies = [
        ('channels', '0002_channel_channel_avatar'),
        ('videos', '0004_videohistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                (
                    'id',
                    models.CharField(
                        default=core.apps.videos.models.generate_playlist_link,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('public', models.BooleanField(default=False)),
                (
                    'channel',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='channels.channel'
                    ),
                ),
                ('videos', models.ManyToManyField(related_name='playlists', to='videos.video')),
            ],
        ),
    ]
