# Generated by Django 5.1.6 on 2025-04-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_initial'),
        ('videos', '0005_videocommentlikeitem_unique_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomment',
            name='likes',
            field=models.ManyToManyField(db_index=True, through='videos.VideoCommentLikeItem', to='channels.channel'),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='reply_level',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1)], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='videocommentlikeitem',
            name='is_like',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
