# Generated by Django 5.1.6 on 2025-03-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='public',
        ),
        migrations.AddField(
            model_name='playlist',
            name='status',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PRIVATE', max_length=7),
        ),
    ]
