# Generated by Django 5.1.6 on 2025-04-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_alter_videocomment_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='yt_link',
        ),
        migrations.AddField(
            model_name='video',
            name='s3_bucket',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='s3_key',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='upload_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
