# Generated by Django 5.1.6 on 2025-04-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_remove_video_file_remove_video_yt_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
