# Generated by Django 5.1.6 on 2025-05-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='upload_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FINISHED', 'Finished')], default='PENDING'),
        ),
    ]
