# Generated by Django 5.1.6 on 2025-05-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_alter_video_upload_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='s3_bucket',
        ),
        migrations.AlterField(
            model_name='video',
            name='upload_status',
            field=models.CharField(choices=[('UPLOADING', 'Uploading'), ('FINISHED', 'Finished')], default='UPLOADING'),
        ),
    ]
