# Generated by Django 5.1.6 on 2025-06-23 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_remove_channel_avatar_s3_bucket'),
        ('videos', '0010_remove_video_s3_bucket_alter_video_upload_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='videocommentlikeitem',
            name='unique_comment_like',
        ),
        migrations.RemoveField(
            model_name='videocomment',
            name='comment',
        ),
        migrations.AddField(
            model_name='videocomment',
            name='reply_comment',
            field=models.ForeignKey(blank=True, help_text='Comment to reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='videos.videocomment'),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='id',
            field=models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='videolike',
            name='is_like',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddConstraint(
            model_name='videocommentlikeitem',
            constraint=models.UniqueConstraint(fields=('author', 'comment'), name='unique_video_comment_like'),
        ),
    ]
