# Generated by Django 5.1.6 on 2025-09-16 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_alter_videocomment_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='videos',
            field=models.ManyToManyField(db_index=True, related_name='playlists', through='videos.PlaylistItem', to='videos.video'),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists_items', to='videos.video'),
        ),
    ]
