# Generated by Django 5.1.6 on 2025-10-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_alter_playlist_videos_alter_playlistitem_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, help_text='Playlist description', null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='status',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PRIVATE', help_text='Playlist privacy status', max_length=7),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(help_text='Playlist name or title', max_length=150),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, db_index=True, help_text='Video description', null=True, verbose_name='Video description'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_reported',
            field=models.BooleanField(default=False, help_text='Indicates that the video has been reported'),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(db_index=True, help_text='Video name or title', max_length=100, verbose_name='Video name or title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='s3_key',
            field=models.CharField(blank=True, help_text='Video S3 file key', null=True, verbose_name='Video S3 file key'),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('UNLISTED', 'Unlisted'), ('PUBLIC', 'Public')], default='PUBLIC', help_text='Video privacy status', max_length=10, verbose_name='Video privacy status'),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload_status',
            field=models.CharField(choices=[('UPLOADING', 'Uploading'), ('FINISHED', 'Finished')], default='UPLOADING', help_text='Video upload status', verbose_name='Video upload status'),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='reply_level',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1)], db_index=True, default=0, help_text='Level of reply'),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='text',
            field=models.TextField(help_text='Comment content'),
        ),
        migrations.AlterField(
            model_name='videocommentlikeitem',
            name='is_like',
            field=models.BooleanField(db_index=True, default=True, help_text='Video comment reaction'),
        ),
        migrations.AlterField(
            model_name='videolike',
            name='is_like',
            field=models.BooleanField(db_index=True, default=True, help_text='Video reaction'),
        ),
    ]
