# Generated by Django 5.1.6 on 2025-03-21 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0002_channel_channel_avatar'),
        ('videos', '0007_alter_playlist_id_playlistitem_alter_playlist_videos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SEXUAL_CONTENT', 'Sexual content'), ('VIOLENT_OR_REPULSIVE_CONTENT', 'Violent or repulsive content'), ('HATEFUL_OR_ABUSIVE_CONTENT', 'Hateful or abusive content'), ('HARASSMENT_OR_BULLYING', 'Harassment or bullying'), ('HARMFUL_OR_DANGEROUS_ACTS', 'Harmful or dangerous acts'), ('MISINFORMATION', 'Misinformation'), ('CHILD_ABUSE', 'Child abuse'), ('PROMOTES_TERRORISM', 'Promotes terrorism'), ('SPAM_OR_MISLEADING', 'Spam or misleading'), ('LEGAL_ISSUE', 'Legal issue'), ('CAPTIONS_ISSUE', 'Captions issue')], db_index=True, max_length=28)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='channels.channel')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
        ),
    ]
