# Generated by Django 5.1.6 on 2025-06-23 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('videos', '0010_remove_video_s3_bucket_alter_video_upload_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoreport',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='videos.video'),
        ),
    ]
