# Generated by Django 5.1.6 on 2025-10-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_videoreport_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoreport',
            name='description',
            field=models.TextField(help_text='Report description'),
        ),
        migrations.AlterField(
            model_name='videoreport',
            name='reason',
            field=models.CharField(choices=[('VIOLENT_OR_REPULSIVE_CONTENT', 'Violent or repulsive content'), ('SEXUAL_CONTENT', 'Sexual content'), ('HATEFUL_OR_ABUSIVE_CONTENT', 'Hateful or abusive content'), ('HARASSMENT_OR_BULLYING', 'Harassment or bullying'), ('HARMFUL_OR_DANGEROUS_ACTS', 'Harmful or dangerous acts'), ('MISINFORMATION', 'Misinformation'), ('CHILD_ABUSE', 'Child abuse'), ('PROMOTES_TERRORISM', 'Promotes terrorism'), ('SPAM_OR_MISLEADING', 'Spam or misleading'), ('LEGAL_ISSUE', 'Legal issue'), ('CAPTIONS_ISSUE', 'Captions issue')], db_index=True, help_text='Report reason', max_length=28),
        ),
    ]
