global:
  scrape_interval: 30s
  scrape_timeout: 30s


scrape_configs:
  - job_name: "web"

    metrics_path: /metrics
    static_configs:
      - targets: ["nginx:443"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __address__
        regex: (.*)
        replacement: api.henwix.space:443