# Generated by Django 5.1.6 on 2025-06-23 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_remove_channel_avatar_s3_bucket'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.CreateModel(
            name='PostCommentItems',
            fields=[
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.BooleanField(default=False)),
                ('reply_level', models.PositiveIntegerField(choices=[(0, 0), (1, 1)], db_index=True, default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_comments_items', to='channels.channel')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_items', to='posts.post')),
                ('reply_comment', models.ForeignKey(blank=True, help_text='Comment to reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.postcommentitems')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='posts_comments', through='posts.PostCommentItems', to='channels.channel'),
        ),
        migrations.CreateModel(
            name='PostCommentLikeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(db_index=True, default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_posts_comments_items', to='channels.channel')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_items', to='posts.postcommentitems')),
            ],
        ),
        migrations.AddField(
            model_name='postcommentitems',
            name='likes',
            field=models.ManyToManyField(blank=True, through='posts.PostCommentLikeItem', to='channels.channel'),
        ),
        migrations.CreateModel(
            name='PostLikeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(db_index=True, default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_posts_items', to='channels.channel')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_items', to='posts.post')),
            ],
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
        migrations.AddConstraint(
            model_name='postcommentlikeitem',
            constraint=models.UniqueConstraint(fields=('author', 'comment'), name='unique_post_comment_like'),
        ),
        migrations.AddConstraint(
            model_name='postlikeitem',
            constraint=models.UniqueConstraint(fields=('channel', 'post'), name='unique_channel_post_like'),
        ),
    ]
