# Generated by Django 5.1.6 on 2025-06-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_remove_channel_avatar_s3_bucket'),
        ('posts', '0002_remove_post_likes_postcommentitems_post_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, through='posts.PostLikeItem', to='channels.channel'),
        ),
    ]
