# Generated by Django 5.1.6 on 2025-06-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_remove_channel_avatar_s3_bucket'),
        ('posts', '0003_post_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostCommentItems',
            new_name='PostCommentItem',
        ),
    ]
