# Generated by Django 5.1.6 on 2025-06-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_remove_channel_avatar_s3_bucket'),
        ('posts', '0004_rename_postcommentitems_postcommentitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', through='posts.PostLikeItem', to='channels.channel'),
        ),
        migrations.AlterField(
            model_name='postcommentitem',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts_comments', through='posts.PostCommentLikeItem', to='channels.channel'),
        ),
    ]
