# Generated by Django 5.1.6 on 2025-10-08 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_alter_channel_avatar_s3_key_alter_channel_country_and_more'),
        ('posts', '0005_alter_post_likes_alter_postcommentitem_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text="Post's author", on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='channels.channel', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Post content', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='postcommentitem',
            name='reply_level',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1)], db_index=True, default=0, help_text='Level of reply'),
        ),
        migrations.AlterField(
            model_name='postcommentitem',
            name='text',
            field=models.TextField(help_text='Comment content'),
        ),
        migrations.AlterField(
            model_name='postcommentlikeitem',
            name='is_like',
            field=models.BooleanField(db_index=True, default=True, help_text='Post comment reaction'),
        ),
        migrations.AlterField(
            model_name='postlikeitem',
            name='is_like',
            field=models.BooleanField(db_index=True, default=True, help_text='Post reaction'),
        ),
    ]
