# Generated by Django 5.1.6 on 2025-02-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_channel_country_videoview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='country',
            field=models.CharField(max_length=40),
        ),
    ]