# Generated by Django 5.1.6 on 2025-02-25 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_videolike_alter_video_options_remove_video_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoview',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_views', to='api.channel'),
        ),
        migrations.AddField(
            model_name='videoview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
