# Generated by Django 5.1.6 on 2025-03-20 16:25

import apps.videos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_remove_playlist_public_playlist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.CharField(db_index=True, default=apps.videos.models.generate_playlist_link, editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='videos.playlist')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='videos',
            field=models.ManyToManyField(db_index=True, through='videos.PlaylistItem', to='videos.video'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='videos',
            field=models.ManyToManyField(db_index=True, through='videos.PlaylistItem', to='videos.video'),
        ),
        migrations.AddConstraint(
            model_name='playlistitem',
            constraint=models.UniqueConstraint(fields=('playlist', 'video'), name='playlist_item_unique'),
        ),
    ]
