# Generated by Django 5.1.6 on 2025-03-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_playlist_id_playlistitem_alter_playlist_videos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
    ]
